export const firebase = {
    LOAD_MATCH_REQUESTED: 'LOAD_MATCH_REQUESTED',
    LOAD_MATCH_FULFILLED: 'LOAD_MATCH_FULFILLED',
    LOAD_MATCH_REJECTED: 'LOAD_MATCH_REJECTED',

    MOVE_MATCH_REQUESTED: 'MOVE_MATCH_REQUESTED',
    MOVE_MATCH_FULFILLED: 'MOVE_MATCH_FULFILLED',
    MOVE_MATCH_REJECTED: 'MOVE_MATCH_REJECTED',

    FIREBASE_UPDATE_REQUESTED: 'FIREBASE_UPDATE_REQUESTED',
    FIREBASE_UPDATE_FULFILLED: 'FIREBASE_UPDATE_FULFILLED',
    FIREBASE_UPDATE_REJECTED: 'FIREBASE_UPDATE_REJECTED',

    FIREBASE_REMOVE_REQUESTED: 'FIREBASE_REMOVE_REQUESTED',
    FIREBASE_REMOVE_FULFILLED: 'FIREBASE_REMOVE_FULFILLED',
    FIREBASE_REMOVE_REJECTED: 'FIREBASE_REMOVE_REJECTED',

    FIREBASE_LISTEN_REQUESTED: 'FIREBASE_LISTEN_REQUESTED',
    FIREBASE_LISTEN_FULFILLED: 'FIREBASE_LISTEN_FULFILLED',
    FIREBASE_LISTEN_REJECTED: 'FIREBASE_LISTEN_REJECTED',

    FIREBASE_LISTEN_CHILD_ADDED: 'FIREBASE_LISTEN_CHILD_ADDED',
    FIREBASE_LISTEN_CHILD_CHANGED: 'FIREBASE_LISTEN_CHILD_CHANGED',
    FIREBASE_LISTEN_CHILD_REMOVED: 'FIREBASE_LISTEN_CHILD_REMOVED',

    FIREBASE_LISTEN_REMOVED: 'FIREBASE_LISTEN_REMOVED',
    FIREBASE_REMOVE_LISTENER_REQUESTED: 'FIREBASE_REMOVE_LISTENER_REQUESTED',
    FIREBASE_REMOVE_ALL_LISTENERS_REQUESTED: 'FIREBASE_REMOVE_ALL_LISTENERS_REQUESTED',
};

export const metaTypes = {
    messages: 'messages',
    chats: 'chats',
    profile: 'profile',
    user: 'user',
    email: 'email',
    password: 'password',
    initial: 'initial_load',
    regular: 'regular_load'
};

export const eventTypes = {
    CHILD_ADDED: 'CHILD_ADDED',
    CHILD_REMOVED: 'CHILD_REMOVED',
    CHILD_CHANGED: 'CHILD_CHANGED',
};